#include <Arduino.h>
#define tiempo1 100
#define tiempo2 500
#define tiempo3 250

//put function declarations here:
int myFunction(int, int);
void RotationClock1();
void RotationClock2();
void RotationAntiClock1();
void RotationAntiClock2();
void Counter();
void Nombre();
void Abecedario();

void setup() {
  pinMode(PB11,OUTPUT);
  pinMode(PA12,OUTPUT);
  pinMode(PB0,OUTPUT);
  pinMode(PB3,OUTPUT);
  pinMode(PB1,OUTPUT);
  pinMode(PB10,OUTPUT);
  pinMode(PA15,OUTPUT);
  pinMode(PA4,OUTPUT);
  pinMode(PA5,OUTPUT);
  pinMode(PA6,OUTPUT);
  pinMode(PB5,OUTPUT);
  pinMode(PB6,OUTPUT);
  pinMode(PA3,OUTPUT);
  pinMode(PB8,OUTPUT);
  pinMode(PA7,OUTPUT);
  pinMode(PB4,OUTPUT);
  pinMode(PB7,OUTPUT);
  
}

void loop() {

RotationClock1();
delay(tiempo2);
RotationClock2();
delay(tiempo2);
RotationAntiClock1();
delay(tiempo2);
RotationAntiClock2();
delay(tiempo2);
Counter();
delay(tiempo2);
Nombre();
delay(tiempo2);
Abecedario();
delay(tiempo2);

}
//put function definitions here:
int myFunction(int x, int y) {
  return x + y;
}

//Rotation Fast
void RotationClock1(){

digitalWrite(PB4,LOW);
digitalWrite(PA15,LOW);
digitalWrite(PB11,HIGH);
delay (tiempo1);
digitalWrite(PB11,LOW);
delay (tiempo1);
digitalWrite(PA12,HIGH);
delay (tiempo1);
digitalWrite(PA12,LOW);
delay (tiempo1);
digitalWrite(PB3,HIGH);
delay (tiempo1);
digitalWrite(PB3,LOW);
delay (tiempo1);
digitalWrite(PB6,HIGH);
delay (tiempo1);
digitalWrite(PB6,LOW);
delay (tiempo1);
digitalWrite(PB8,HIGH);
delay (tiempo1);
digitalWrite(PB8,LOW);
delay (tiempo1);
digitalWrite(PA3,HIGH);
delay (tiempo1);
digitalWrite(PA3,LOW);
delay (tiempo1);
digitalWrite(PA4,HIGH);
delay (tiempo1);
digitalWrite(PA4,LOW);
delay (tiempo1);
digitalWrite(PB0,HIGH);
delay (tiempo1);
digitalWrite(PB0,LOW);
delay (tiempo1);
}

//Rotation Slow
void RotationClock2(){

digitalWrite(PB4,LOW);
digitalWrite(PA15,LOW);
digitalWrite(PB11,HIGH);
delay (tiempo2);
digitalWrite(PB11,LOW);
delay (tiempo2);
digitalWrite(PA12,HIGH);
delay (tiempo2);
digitalWrite(PA12,LOW);
delay (tiempo2);
digitalWrite(PB3,HIGH);
delay (tiempo2);
digitalWrite(PB3,LOW);
delay (tiempo2);
digitalWrite(PB6,HIGH);
delay (tiempo2);
digitalWrite(PB6,LOW);
delay (tiempo2);
digitalWrite(PB8,HIGH);
delay (tiempo2);
digitalWrite(PB8,LOW);
delay (tiempo2);
digitalWrite(PA3,HIGH);
delay (tiempo2);
digitalWrite(PA3,LOW);
delay (tiempo2);
digitalWrite(PA4,HIGH);
delay (tiempo2);
digitalWrite(PA4,LOW);
delay (tiempo2);
digitalWrite(PB0,HIGH);
delay (tiempo2);
digitalWrite(PB0,LOW);
delay (tiempo2);
}

//Rotation Anticlock Fast
void RotationAntiClock1(){

digitalWrite(PB4,LOW);
digitalWrite(PA15,LOW);
digitalWrite(PB11,HIGH);
delay (tiempo1);
digitalWrite(PB11,LOW);
delay (tiempo1);
digitalWrite(PB0,HIGH);
delay (tiempo1);
digitalWrite(PB0,LOW);
delay (tiempo1);
digitalWrite(PA4,HIGH);
delay (tiempo1);
digitalWrite(PA4,LOW);
delay (tiempo1);
digitalWrite(PA3,HIGH);
delay (tiempo1);
digitalWrite(PA3,LOW);
delay (tiempo1);
digitalWrite(PB8,HIGH);
delay (tiempo1);
digitalWrite(PB8,LOW);
delay (tiempo1);
digitalWrite(PB6,HIGH);
delay (tiempo1);
digitalWrite(PB6,LOW);
delay (tiempo1);
digitalWrite(PB3,HIGH);
delay (tiempo1);
digitalWrite(PB3,LOW);
delay (tiempo1);
digitalWrite(PA12,HIGH);
delay (tiempo1);
digitalWrite(PA12,LOW);
delay (tiempo1);
}
  
//Rotation Anticlock Slow
void RotationAntiClock2(){

digitalWrite(PB4,LOW);
digitalWrite(PA15,LOW);
digitalWrite(PB11,HIGH);
delay (tiempo2);
digitalWrite(PB11,LOW);
delay (tiempo2);
digitalWrite(PB0,HIGH);
delay (tiempo2);
digitalWrite(PB0,LOW);
delay (tiempo2);
digitalWrite(PA4,HIGH);
delay (tiempo2);
digitalWrite(PA4,LOW);
delay (tiempo2);
digitalWrite(PA3,HIGH);
delay (tiempo2);
digitalWrite(PA3,LOW);
delay (tiempo2);
digitalWrite(PB8,HIGH);
delay (tiempo2);
digitalWrite(PB8,LOW);
delay (tiempo2);
digitalWrite(PB6,HIGH);
delay (tiempo2);
digitalWrite(PB6,LOW);
delay (tiempo2);
digitalWrite(PB3,HIGH);
delay (tiempo2);
digitalWrite(PB3,LOW);
delay (tiempo2);
digitalWrite(PA12,HIGH);
delay (tiempo2);
digitalWrite(PA12,LOW);
delay (tiempo2);
}

//COUNTER 0-9
void Counter(){

digitalWrite(PB4,LOW);
digitalWrite(PA15,LOW);
//Cero
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (1000);

//Uno
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);

//Dos
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);
//Tres
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);
//Cuatro
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);
//Cinco
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);
//Seis
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);
//Siete
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);
//Ocho
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);
//Nueve
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);
}

void Nombre(){

digitalWrite(PB4,LOW);
digitalWrite(PA15,LOW);
 //Primer Nombre (Ronald)
//R
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (1000);

//O
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//N
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB1,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (tiempo3);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB1,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (1000);

//A
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);

//L
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//D
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB10,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB10,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//Segundo Nombre (Stiward)

//S
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//T
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB10,HIGH);
delay (10);
digitalWrite(PA6,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB10,LOW);
delay (10);
digitalWrite(PA6,LOW);
delay (1000);


//I
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB10,HIGH);
delay (10);
digitalWrite(PA6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB10,LOW);
delay (10);
digitalWrite(PA6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//W
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA5,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (tiempo3);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA5,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (1000);

//A
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);

//R
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (1000);

//D
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB10,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB10,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//Primer Apellido (Valderrama)

//V
digitalWrite(PB1,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (tiempo3);
digitalWrite(PB1,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (1000);

//A
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);

//L
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//D
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB10,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB10,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//E
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//R
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (1000);

//R
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (1000);

//A
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);

//M
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB1,HIGH);
delay (10);
digitalWrite(PA15,HIGH);
delay (tiempo3);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PB1,LOW);
delay (10);
digitalWrite(PA15,LOW);
delay (1000);

//A
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);

//Segundo Apellido (Cuellar)

//C
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//U
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//E
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//L
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//L
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//A
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);

//R
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (1000);
}


//ABECEDARIO
void Abecedario(){

digitalWrite(PB4,LOW);
digitalWrite(PA15,LOW);

//A
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);

//B
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB10,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB10,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//C
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//D
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB10,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB10,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//E
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//F
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (1000);

//G
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//H
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (tiempo3);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (1000);


//I
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB10,HIGH);
delay (10);
digitalWrite(PA6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB10,LOW);
delay (10);
digitalWrite(PA6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//J
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//K
digitalWrite(PA15,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (tiempo3);
digitalWrite(PA15,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (1000);

//L
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//M
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PB1,HIGH);
delay (10);
digitalWrite(PA15,HIGH);
delay (tiempo3);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PB1,LOW);
delay (10);
digitalWrite(PA15,LOW);
delay (1000);

//N
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB1,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (tiempo3);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB1,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (1000);

//O
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//P
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (1000);

//Q
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//R
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (1000);

//S
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

//T
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PB10,HIGH);
delay (10);
digitalWrite(PA6,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PB10,LOW);
delay (10);
digitalWrite(PA6,LOW);
delay (1000);

//V
digitalWrite(PB1,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (tiempo3);
digitalWrite(PB1,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (1000);

//W
digitalWrite(PA4,HIGH);
delay (10);
digitalWrite(PB6,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (10);
digitalWrite(PA5,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (tiempo3);
digitalWrite(PA4,LOW);
delay (10);
digitalWrite(PB6,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (10);
digitalWrite(PA5,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (1000);

//X
digitalWrite(PB1,HIGH);
delay (10);
digitalWrite(PA15,HIGH);
delay (10);
digitalWrite(PA5,HIGH);
delay (10);
digitalWrite(PB5,HIGH);
delay (tiempo3);
digitalWrite(PB1,LOW);
delay (10);
digitalWrite(PA15,LOW);
delay (10);
digitalWrite(PA5,LOW);
delay (10);
digitalWrite(PB5,LOW);
delay (1000);

//Y
digitalWrite(PA6,HIGH);
delay (10);
digitalWrite(PA7,HIGH);
delay (10);
digitalWrite(PB4,HIGH);
delay (10);
digitalWrite(PB0,HIGH);
delay (10);
digitalWrite(PB3,HIGH);
delay (tiempo3);
digitalWrite(PA6,LOW);
delay (10);
digitalWrite(PA7,LOW);
delay (10);
digitalWrite(PB4,LOW);
delay (10);
digitalWrite(PB0,LOW);
delay (10);
digitalWrite(PB3,LOW);
delay (1000);

//Z
digitalWrite(PB11,HIGH);
delay (10);
digitalWrite(PA12,HIGH);
delay (10);
digitalWrite(PA15,HIGH);
delay (10);
digitalWrite(PA5,HIGH);
delay (10);
digitalWrite(PA3,HIGH);
delay (10);
digitalWrite(PB8,HIGH);
delay (tiempo3);
digitalWrite(PB11,LOW);
delay (10);
digitalWrite(PA12,LOW);
delay (10);
digitalWrite(PA15,LOW);
delay (10);
digitalWrite(PA5,LOW);
delay (10);
digitalWrite(PA3,LOW);
delay (10);
digitalWrite(PB8,LOW);
delay (1000);

}




